# Generated by Django 5.2.1 on 2025-06-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('inferred_target', models.CharField(blank=True, max_length=255, null=True)),
                ('data_shape', models.CharField(max_length=50)),
                ('result_json', models.JSONField()),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='SalesRecord',
        ),
    ]
