# Generated by Django 5.2.1 on 2025-06-06 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_savedresult_delete_salesrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='2025-06-06 00:00:00'),
            preserve_default=False,
        ),
    ]
