# Generated by Django 5.2.1 on 2025-06-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_remove_savedresult_result_json_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savedresult',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='savedresult',
            name='data_shape',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='savedresult',
            name='eda_result',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='savedresult',
            name='file_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='savedresult',
            name='model_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
