# Generated by Django 5.2.1 on 2025-06-06 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0005_remove_savedresult_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedresult',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 6, 15, 36, 24, 866328, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='savedresult',
            name='data_shape',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='savedresult',
            name='eda_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='savedresult',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='savedresult',
            name='model_result',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
