# Generated by Django 5.2.1 on 2025-06-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_remove_savedresult_created_at_savedresult_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedresult',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
