# Generated by Django 5.2.1 on 2025-08-19 07:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_alter_savedresult_model_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='savedresult',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddConstraint(
            model_name='savedresult',
            constraint=models.UniqueConstraint(fields=('owner', 'file_name', 'model_name'), name='unique_owner_file_model'),
        ),
    ]
